name: usdarobot
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  bluesky: ^0.16.0
  bluesky_text: ^0.6.9
  dart_rss: ^3.0.3
  html: ^0.15.4
  http: ^1.2.2
  sqlite3: ^2.4.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
